machine:
    services:
        - docker

dependencies:
    override:
        - docker info
        - docker pull opencog/opencog-deps
        - docker images opencog/opencog-deps

test:
    override:
        - docker run -v $PWD:/cogutil -it opencog/opencog-deps /bin/sh -c "cd /cogutil && /tmp/octool -bti"

general:
  artifacts:
    - "~/cogutil/build/tests/Testing/Temporary" # Test logs
